set t_ut=

" Search folders recursivelly
set path+=**

" Display all matching files when we tab complete
set wildmenu

command! MakeTags !ctags -R .


let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_listsyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()

